version: '3'
services:

  database:
    image: postgres:11.1
    environment:
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: database
      POSTGRES_USER: root
    ports:
      - 5433:5432
    networks:
      - app-tier
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d

  python:
    build:
      context: ./python
      dockerfile: Dockerfile
    depends_on:
      - postgres_db
    networks:
      - app-tier
    command:
      tail -f /dev/null


networks:
  app-tier:
    driver: bridge